name: smpc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  shimmer: ^2.0.0
  flutter_svg: ^1.1.1+1
  cached_network_image: ^3.2.1
  firebase_storage: ^10.3.3
  lottie: ^1.3.0
  adaptive_dialog: ^1.6.4+2
  image_picker: ^0.8.5+3
  cloud_firestore: ^3.4.1
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  modal_bottom_sheet: ^2.1.0
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/json/
    - assets/icons/
 

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
